Feature/events application
Rumbie-Mudzie7/private-events pull request #1
Opened 2020-10-08 22:32 UTC by Rumbie-Mudzie7

The following procedures were implemented in the private-events milestone:

-  Users were allowed to create events and then manage user signups.
-  Users were allowed to send invitations and parties.
-  Events could take place at a specific date and at a location.
-  many-to-many relationship associations between models.
-  belongs-to relationship association on models that belong to the User model.

2020-10-09 00:31 UTC, uche-inyama requested changes
## Changes required

Hi team how is it going   :wave: 

Let's work on some additional features and necessary updates:

* [x] The event's show page should also display the list of those attending the event ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

* [ ] The user's show page should display events the user has created and events that the user is attending, separated in past and upcoming ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

* [ ] There are commented lines of code, in one of your models, I have left a comment below.

* [ ] Remove if/else statement in your view files, refactor them in their corresponding helper files.

* [ ] There are no RSpec tests, kindly implement your test with RSpec. I can see you wrote your test with the Minitest approach.

Make these changes, when you are done submit another form for a code review.

#### ``` Have a great day ``` 


``` Uchechkwu Henry Inyama```

2020-10-09 00:31 UTC, uche-inyama commented on app/controllers/users_controller.rb
> +    # @upcoming_events = current_user.attended_events.upcoming_events
Delete these commented lines of code.

2020-10-09 00:31 UTC, uche-inyama commented on app/models/user.rb
> +  # has_many :attended_events, through: :event_attendings
Remove these commented lines of code.

2020-10-13 08:32 UTC, rOluochKe approved these changes
Hello @Rumbie-Mudzie7 and @ClaytonSiby 
### You got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-10-13 08:53 UTC, merged